# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:07
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_mozillian', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('want_to_contribute', models.BooleanField(default=False)),
                ('contribution_area', models.CharField(choices=[('TE', 'Technical'), ('NT', 'Non-Technical'), ('BO', 'Both')], default='BO', max_length=2)),
                ('submitted_on', models.DateTimeField(default=datetime.datetime(2016, 2, 10, 21, 7, 17, 171663))),
                ('query_or_suggestions', models.TextField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
